package com.zhuani21.review.mapper;

import com.zhuani21.review.bean.LoginAuth;
import com.zhuani21.review.bean.LoginAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_auth
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    int countByExample(LoginAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_auth
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    int deleteByExample(LoginAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_auth
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_auth
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    int insert(LoginAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_auth
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    int insertSelective(LoginAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_auth
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    List<LoginAuth> selectByExample(LoginAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_auth
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    LoginAuth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_auth
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    int updateByExampleSelective(@Param("record") LoginAuth record, @Param("example") LoginAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_auth
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    int updateByExample(@Param("record") LoginAuth record, @Param("example") LoginAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_auth
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    int updateByPrimaryKeySelective(LoginAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_auth
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    int updateByPrimaryKey(LoginAuth record);
}