package com.zhuani21.review.bean;

public class Code {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.id
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.type
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.code
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.name
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.parent_id
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.id
     *
     * @return the value of code.id
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.id
     *
     * @param id the value for code.id
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.type
     *
     * @return the value of code.type
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.type
     *
     * @param type the value for code.type
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.code
     *
     * @return the value of code.code
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.code
     *
     * @param code the value for code.code
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.name
     *
     * @return the value of code.name
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.name
     *
     * @param name the value for code.name
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.parent_id
     *
     * @return the value of code.parent_id
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.parent_id
     *
     * @param parentId the value for code.parent_id
     *
     * @mbggenerated Tue Jan 12 17:37:37 CST 2016
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}